bonitasoft/bonita-admin-application

applications/bonita-admin-application.xml
- remove unavailable pages
- change the home page to admin process list
=> feat(pages) remove unavailable pages

applications/bonita-admin-application.xml, pom.xml
To be merged only once the profile list page is renamed
=> fix(profile page name) update page name and artifact name

community/applications/bonita-admin-application.xml, pom.xml, subscription/applications/bonita-admin-application-sp.xml
covers [BR-572](https://bonitasoft.atlassian.net/browse/BR-572)
=> feat(admin case details): Upgrade version to v2

community/applications/bonita-admin-application.xml, subscription/applications/bonita-admin-application-sp.xml
* new name : Bonita Administrator Application
Covers [BR-606](https://bonitasoft.atlassian.net/browse/BR-606)
=> feat(admin app) update app name

community/applications/bonita-admin-application.xml, pom.xml, subscription/applications/bonita-admin-application-sp.xml
Is connected to [#480](https://github.com/bonitasoft/bonita-web-pages/pull/480)
Covers [BR-635](https://bonitasoft.atlassian.net/browse/BR-635)
=> fix (layout): Change layout version

.gitignore, community/applications/bonita-admin-application.xml, pom.xml, subscription/applications/bonita-admin-application-sp.xml
covers [RUNTIME-97](https://bonitasoft.atlassian.net/browse/RUNTIME-97)
is related to [#8](bonitasoft/bonita-web-pages-internal#8)
=> feat(artifacts): Upgrade artifact versions after tab improvement

community/applications/bonita-admin-application.xml, pom.xml, subscription/applications/bonita-admin-application-sp.xml
* add UID admin case list to app descriptor
Covers 
[RUNTIME-135](https://bonitasoft.atlassian.net/browse/RUNTIME-135)
=> feat(admin case list) add UID page to app descriptor

community/applications/bonita-admin-application.xml, pom.xml, subscription/applications/bonita-admin-application-sp.xml
* use latest version of admin group list to benefit from the status code update
Covers [RUNTIME-256](https://bonitasoft.atlassian.net/browse/RUNTIME-256)
=> feat(admin group list) upgrade version

pom.xml, subscription/applications/bonita-admin-application-sp.xml
* this is a artifact in itself, also declare dependencies on the pages in order to let consumers of that artifact be able to retrieve all pages required
* rename group Id
* rename SP app token
Relates to [RUNTIME-183](https://bonitasoft.atlassian.net/browse/RUNTIME-183)
=> feat: publish xml of the application

.gitignore, community/pom.xml, community/zip-with-resources-assembly.xml, subscription/pom.xml, subscription/zip-with-resources-assembly.xml
* add new zip with resources package including the built version of the application pages
* only bundle the non provided pages (other pages are provided by the super admin app)
Covers [RUNTIME-263](https://bonitasoft.atlassian.net/browse/RUNTIME-263)
=>  feat(packaging): add new zip with resources package

community/applications/bonita-admin-application.xml, subscription/applications/bonita-admin-application-sp.xml
Upgrade version of users, roles, profiles, and resources list pages.
=> feat (list pages): Upgrade version

community/applications/bonita-admin-application.xml, community/bonita-distrib/bonita-admin-application.xml, subscription/applications/bonita-admin-application-sp.xml, subscription/bonita-distrib/bonita-admin-application-sp.xml
Relates to [RUNTIME-366](https://bonitasoft.atlassian.net/browse/RUNTIME-366)
=> feat: add description to the application

infrastructure/change_version.sh
exclude bos-distrib folders when changing the release version
=> fix(release): update change version script

community/bos-distrib/applications/bonita-admin-application.xml, subscription/bos-distrib/applications/bonita-admin-application-sp.xml
covers [RUNTIME-472](https://bonitasoft.atlassian.net/browse/RUNTIME-472)
relates to [#111](https://github.com/bonitasoft/bonita-web-pages-internal/pull/111)
=> chore(layout): Update Bonita layout version

community/bos-distrib/applications/bonita-admin-application.xml, subscription/bos-distrib/applications/bonita-admin-application-sp.xml
covers [RUNTIME-1011](https://bonitasoft.atlassian.net/browse/RUNTIME-1011)
relates to [#5](https://github.com/bonitasoft/bonita-web-pages-sp/pull/5)
=> feat(admin case list): Update version of the page

community/pom.xml, subscription/bos-distrib/applications/bonita-admin-application-sp.xml, subscription/pom.xml
Covers [RUNTIME-1268](https://bonitasoft.atlassian.net/browse/RUNTIME-1268)
=> Feat (Admin application): Add BPMN Visualization pages to the admin application

community/bos-distrib/applications/bonita-admin-application.xml, subscription/bos-distrib/applications/bonita-admin-application-sp.xml
Covers [RUNTIME-1301](https://bonitasoft.atlassian.net/browse/RUNTIME-1301)
=> Feat (Admin application): Update application pages version

community/bos-distrib/applications/bonita-admin-application.xml, community/pom.xml, subscription/bos-distrib/applications/bonita-admin-application-sp.xml, subscription/pom.xml
Covers [RUNTIME-1481](https://bonitasoft.atlassian.net/browse/RUNTIME-1481)
=> Feat (Admin application): Upgrade page version

community/bos-distrib/applications/bonita-admin-application.xml, subscription/bos-distrib/applications/bonita-admin-application-sp.xml
Covers [RUNTIME-1583](https://bonitasoft.atlassian.net/browse/RUNTIME-1583)
=> Feat (Admin application): Upgrade profile list page version

community/bos-distrib/applications/bonita-admin-application.xml, subscription/bos-distrib/applications/bonita-admin-application-sp.xml
Depends on https://github.com/bonitasoft/bonita-web-pages-sp/pull/166
=> fix(layout): update version

community/bos-distrib/applications/bonita-admin-application.xml, subscription/bos-distrib/applications/bonita-admin-application-sp.xml
covers [RUNTIME-1639](https://bonitasoft.atlassian.net/browse/RUNTIME-1639)
Relates to [#161](https://github.com/bonitasoft/bonita-web-pages-sp/pull/161)
[RUNTIME-1639]: https://bonitasoft.atlassian.net/browse/RUNTIME-1639?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(case list and details): update page versions

community/bos-distrib/applications/bonita-admin-application.xml, subscription/bos-distrib/applications/bonita-admin-application-sp.xml
Covers [RUNTIME-1648](https://bonitasoft.atlassian.net/browse/RUNTIME-1648)
[RUNTIME-1648]: https://bonitasoft.atlassian.net/browse/RUNTIME-1648?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix(resource list): update version

community/bos-distrib/applications/bonita-admin-application.xml, community/pom.xml, subscription/bos-distrib/applications/bonita-admin-application-sp.xml, subscription/pom.xml
Covers [DEV-220](https://bonitasoft.atlassian.net/browse/DEV-220)
Depends on bonitasoft/bonita-web-pages-sp/pull/218
[DEV-220]: https://bonitasoft.atlassian.net/browse/DEV-220?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=>  chore(update pages versions): follow bonita-web-pages updates

subscription/bos-distrib/applications/bonita-admin-application-sp.xml
covers [DEV-272](https://bonitasoft.atlassian.net/browse/DEV-272)
relates to [#225](https://github.com/bonitasoft/bonita-web-pages-sp/pull/225)
[DEV-272]: https://bonitasoft.atlassian.net/browse/DEV-272?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(visu pages): update visu pages on dev

community/bos-distrib/applications/bonita-admin-application.xml, subscription/bos-distrib/applications/bonita-admin-application-sp.xml
Covers [RUNTIME-1049](https://bonitasoft.atlassian.net/browse/RUNTIME-1049)
[RUNTIME-1049]: https://bonitasoft.atlassian.net/browse/RUNTIME-1049?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Chore(Admin user list): Update page version

community/bos-distrib/applications/bonita-admin-application.xml, subscription/bos-distrib/applications/bonita-admin-application-sp.xml
covers [RUNTIME-1364](https://bonitasoft.atlassian.net/browse/RUNTIME-1364)
relates to [#256](https://github.com/bonitasoft/bonita-web-pages-sp/pull/256)
[RUNTIME-1364]: https://bonitasoft.atlassian.net/browse/RUNTIME-1364?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(pages): update page versions

community/bos-distrib/applications/bonita-admin-application.xml, subscription/bos-distrib/applications/bonita-admin-application-sp.xml
Covers [RUNTIME-1713](https://bonitasoft.atlassian.net/browse/RUNTIME-1713)
related to [#260](https://github.com/bonitasoft/bonita-web-pages-sp/pull/260)
[RUNTIME-1713]: https://bonitasoft.atlassian.net/browse/RUNTIME-1713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(Admin case list): update page version on 7.15.x

community/bos-distrib/applications/bonita-admin-application.xml, subscription/bos-distrib/applications/bonita-admin-application-sp.xml
covers [RUNTIME-1713](https://bonitasoft.atlassian.net/browse/RUNTIME-1713)
relates to [#267](https://github.com/bonitasoft/bonita-web-pages-sp/pull/267)
[RUNTIME-1713]: https://bonitasoft.atlassian.net/browse/RUNTIME-1713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(case list): update page version

community/bos-distrib/applications/bonita-admin-application.xml, subscription/bos-distrib/applications/bonita-admin-application-sp.xml
Covers [RUNTIME-1713](https://bonitasoft.atlassian.net/browse/RUNTIME-1713)
Related to [#272](https://github.com/bonitasoft/bonita-web-pages-sp/pull/272)
[RUNTIME-1713]: https://bonitasoft.atlassian.net/browse/RUNTIME-1713?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore (Admin application): update admin task details page version

community/bos-distrib/applications/bonita-admin-application.xml, subscription/bos-distrib/applications/bonita-admin-application-sp.xml
Covers [RUNTIME-1806](https://bonitasoft.atlassian.net/browse/RUNTIME-1806)
[RUNTIME-1806]: https://bonitasoft.atlassian.net/browse/RUNTIME-1806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat (bonita admin application): update page versions

community/bos-distrib/applications/bonita-admin-application.xml, subscription/bos-distrib/applications/bonita-admin-application-sp.xml
Covers [RUNTIME-1806](https://bonitasoft.atlassian.net/browse/RUNTIME-1806)
[RUNTIME-1806]: https://bonitasoft.atlassian.net/browse/RUNTIME-1806?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat (bonita admin application): update application page versions

community/bos-distrib/applications/bonita-admin-application.xml, community/pom.xml, subscription/bos-distrib/applications/bonita-admin-application-sp.xml, subscription/pom.xml
Covers [RUNTIME-1825](https://bonitasoft.atlassian.net/browse/RUNTIME-1825)
[RUNTIME-1825]: https://bonitasoft.atlassian.net/browse/RUNTIME-1825?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat (admin application): update page version

community/src/main/resources/bonita-distrib/bonita-admin-application.xml, community/src/main/resources/bos-distrib/applications/bonita-admin-application.xml, subscription/src/main/resources/bonita-distrib/bonita-admin-application-sp.xml, subscription/src/main/resources/bos-distrib/applications/bonita-admin-application-sp.xml
Related to [BPM-110](https://bonitasoft.atlassian.net/browse/BPM-110)
[BPM-110]: https://bonitasoft.atlassian.net/browse/BPM-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore(xmlns): bump application-xml-schema from 1.0 to 1.1

community/pom.xml, community/src/main/resources/bos-distrib/applications/bonita-admin-application.xml, subscription/pom.xml, subscription/src/main/resources/bos-distrib/applications/bonita-admin-application-sp.xml
Related to [BPM-114](https://bonitasoft.atlassian.net/browse/BPM-114)
[BPM-114]: https://bonitasoft.atlassian.net/browse/BPM-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(layout): upgrade layout version

community/bos-distrib/applications/bonita-admin-application.xml, community/pom.xml, subscription/bos-distrib/applications/bonita-admin-application-sp.xml, subscription/pom.xml
Covers [RUNTIME-1889](https://bonitasoft.atlassian.net/browse/RUNTIME-1889)
[RUNTIME-1889]: https://bonitasoft.atlassian.net/browse/RUNTIME-1889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat (layout): update layout version

community/pom.xml, community/src/main/resources/bos-distrib/applications/bonita-admin-application.xml, subscription/pom.xml, subscription/src/main/resources/bos-distrib/applications/bonita-admin-application-sp.xml
Covers [BPM-312](https://bonitasoft.atlassian.net/browse/BPM-312)
[BPM-312]: https://bonitasoft.atlassian.net/browse/BPM-312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat (admin task details): update page version

community/src/main/resources/bos-distrib/applications/bonita-admin-application.xml, subscription/src/main/resources/bos-distrib/applications/bonita-admin-application-sp.xml
follow changes of bonitasoft/bonita-web-pages-sp/pull/560
=> feat(case details): update page version

subscription/src/main/resources/bos-distrib/applications/bonita-admin-application-sp.xml
to be merged with bonitasoft/bonita-web-pages-sp/pull/563
=> feat(case visu): allow to display archived subprocess

community/src/main/resources/bos-distrib/applications/bonita-admin-application.xml, subscription/src/main/resources/bos-distrib/applications/bonita-admin-application-sp.xml
covers [BPM-357](https://bonitasoft.atlassian.net/browse/BPM-357)
[BPM-357]: https://bonitasoft.atlassian.net/browse/BPM-357?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat(admin case and task list): update version
